### ISSUE TITLE
shortest possible match | non greedy match

### ISSUE THREAD

**Issue by sprungknoedl** [blynn/nex#12]
There is currently no possibility I could find to get the shortest possible match (non-greedy behaviour). 

There should be a possibility to split the following snippet:

``` PHP
<?php
  b
?>
text
<?php
  a
?>
```

to these 2 matches:

```
<?php
  b
?>
```

and

```
<?php
  a
?>
```

Currently the regex `/<\?php.*\?>/` matches the whole text.

Or did I simply miss something?
Thanks

**Comment by purpleidea** [comment]
For anyone searching for the above broken link, here is a mirror:

http://www.cas.mcmaster.ca/~kahl/SE3E03/2006/flex/flex_82.html
