### ISSUE TITLE
no way to change func (yylex Lexer) Error(e string)

### ISSUE THREAD

**Issue by ellisonch** [blynn/nex#24]
As far as I can tell, there doesn't seem to be a way to change the `func (yylex Lexer) Error(e string)` function.  This function gets called automatically from a `go tool yacc` generated parser, so it would be nice to be able to customize it.

**Comment by purpleidea** [comment]
UTSL...

add -e to the nex call and add the function in your foo.nex:


```
// YOLO
func (yylex Lexer) Error(e string) {
        fmt.Println("WE ERROR!!!")
        panic(e)
}
```

**Comment by purpleidea** [comment]
Closing because I think this is solved. If not please open a new issue.
