### ISSUE TITLE
Case insensitive regular expressions

### ISSUE THREAD

**Issue by astrothing** [blynn/nex#46]
Is there a way to define case insensitive regular expressions? I am making a SQL parser and I need to be able to parse correctly `SELECT`, `select` or any of its variants.

I do know that Flex has `%option caseless`, is there something similar for Nex?

**Comment by purpleidea** [comment]
What about a [Ss][Ee][Ll][Ee][Cc][Tt] sort of thing? (you get the idea...)
But I'd keep it simple and disallow a mixed case token. Eg: SeLeCt should be a compile error.

**Comment by astrothing** [comment]
@purpleidea
> What about a [Ss][Ee][Ll][Ee][Cc][Tt] sort of thing? (you get the idea...)
But I'd keep it simple and disallow a mixed case token. Eg: SeLeCt should be a compile error.

I guess that would be the simplest solution. Thanks for replying and for the suggestion.
