### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by astrothing** [blynn/nex#47]
I'm guessing that Nex is not thread safe if it uses globals, am I wrong? My program needs to be able to parse in multiple threads and I'm wondering if I will need to lock a mutex for every time Lex will be called.

**Comment by purpleidea** [comment]
Where do you see globals?

**Comment by astrothing** [comment]
@purpleidea My bad :man_facepalming: Just because Flex uses globals I wrongly assumed that Nex does too. I should have checked before asking, I apologize for making this issue.

**Comment by purpleidea** [comment]
no worries, afaik it does not.
