### ISSUE TITLE
ability to create my own error handler

### ISSUE THREAD

**Issue by andrewrk** [blynn/nex#5]
what if I don't want to panic(err) when there is a parsing error?

**Comment by drewwells** [comment]
This is not going to work, the parser won't satisfy the *Lexer interface now

```
-> % nex -e desk.nex && go tool yacc desk.y && go run y.go desk.nn.go
# command-line-arguments
./desk.nn.go:387: cannot use NewLexer(os.Stdin) (type *Lexer) as type yyLexer in argument to yyParse:
	*Lexer does not implement yyLexer (missing Error method) 
```

Since the stacktrace from yacc parser is largely useless, we could change Error() to return a string. This can be handled gracefully by parsers generated by yacc
